blog_main_part/urls.py
"""这个文件定义应用blog_main_part的具体URL模式"""

from django.conf.urls import url

from . import views

# 告诉 Django 这个URL文件用于这个应用
app_name = 'blog_main_part'

urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),

    # 文章详情页
    url(r'^post/(?P<my_args>\d+)/$', views.detail, name='detail'),

    # 归档时间的详情页
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',
        views.archives, name='archives'),

    # 文章分类的详情页
    url(r'^category/(?P<my_args>\d+)/$', views.category, name='category'),
]

comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'

urlpatterns = [
    url(r'^comment/post/(?P<post_args>[0-9]+)/$',
        views.post_comment, name='post_comment'),
]

my_first_blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # 定义管理员页面的基础URL
    url(r'^admin/', include(admin.site.urls)),

    # 定义应用blog_main_part的基础URL
    url(r'', include('blog_main_part.urls', namespace='blog_main_part')),

    # 定义应用comments的URL
    url(r'', include('comments.urls')),
]

blog_main_part/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Category(models.Model):
    """对文章进行分类的数据模型"""
    name = models.CharField(max_length=100)

    def __str__(self):
        """返回模型生成的数据"""
        return self.name


class Tag(models.Model):
    """给文章打上标签的数据模型"""
    name = models.CharField(max_length=100)

    def __str__(self):
        """返回模型生成的数据"""
        return self.name


class Post(models.Model):
    """一篇文章的数据模型"""
    title = models.CharField(max_length=80)
    body = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now_add=True)

    # blank属性意为是否允许为空值
    excerpt = models.CharField(max_length=200, blank=True)

    # 让一篇文章与它的唯一分类关联（一对多）
    category = models.ForeignKey(Category)

    # 一篇文章有多个标签，这些相同的标签页可能对应多篇文章（多对多）
    tags = models.ManyToManyField(Tag, blank=True)

    # 让一篇文章与它的唯一作者关联（一对多）
    author = models.ForeignKey(User)

    # 记录阅读量
    views = models.PositiveIntegerField(default=0)

    class Meta:
        """把博客文章降序排列(改变上面的属性date_added)"""
        ordering = ['-created_time']
        ordering = ['-modified_time']

    def __str__(self):
        """返回模型生成的数据"""
        return self.title

    def get_absolute_url(self):
        """给视图函数detail返回id属性，方便生成对应url"""
        return reverse('blog_main_part:detail', kwargs={'my_args': self.id})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

comments/models.py
from blog_main_part.models import Post
from django.db import models


class Comment(models.Model):
    """评论应用的数据库模型"""

    # 用户的名字
    name = models.CharField(max_length=100)

    # 用户的邮箱
    email = models.EmailField(max_length=255)

    # 记录用户的个人网站
    url = models.URLField(blank=True)

    # 用户发表的内容
    text = models.TextField()

    # 创建时间
    created_time = models.DateTimeField(auto_now_add=True)

    # 这条评论关联到唯一那篇文章
    post = models.ForeignKey(Post, related_name='comments')

    def __str__(self):
        return self.text[:20] + "..."

comments/forms.py
from django import forms

from .models import Comment


class CommentsForms(forms.ModelForm):

    class Meta:
        # 指定这个表单对应Comments模型
        model = Comment

        # 指定要显示的字段
        fields = ['name', 'email', 'url', 'text']

        # 指定了各个字段在前端渲染的输入框类型
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': "你的昵称",
            }),
            'email': forms.TextInput(attrs={
                'placeholder': "邮箱",
            }),
            'url': forms.TextInput(attrs={
                'placeholder': "个人网址",
            }),
        }

blog_main_part/views.py
import markdown
from comments.forms import CommentsForms
from django.shortcuts import get_object_or_404, render
from django.utils.text import slugify
from django.views.decorators.cache import cache_page
from markdown.extensions.toc import TocExtension

from .models import Category, Post


# @cache_page(60 * 15) 对单个视图函数使用缓存（暂不使用）
def index(request):
    """主页，及其数据处理逻辑"""
    post_list = Post.objects.all()  # 获取Post数据模型的全部数据
    return render(request, 'blog_main_part/index.html', {'post_list': post_list})


def detail(request, my_args):
    """文章详情页，及其数据处理逻辑"""
    post = get_object_or_404(Post, id=my_args)
    post.increase_views()
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        TocExtension(slugify=slugify)])  # slugify参数处理中文锚值显示问题
    post.body = md.convert(post.body)  # 用convert方法将markdown文本渲染成html
    form = CommentsForms()
    # 获取这篇post下的全部评论
    comment_list = post.comments.all()
    context = {'post': post,
               'form': form,
               'comment_list': comment_list,
               'toc': md.toc}  # 一旦调用convert方法后，md就会多出一个toc属性

    return render(request, 'blog_main_part/detail.html', context=context)


def archives(request, year, month):
    """归档时间详情页"""

    # created_time.year，这个实例调用属性，但由于这里做参数，故改为两个下划线 __
    post_list = Post.objects.filter(
        created_time__year=year, created_time__month=month)
    return render(request, 'blog_main_part/index.html', {'post_list': post_list})


def category(request, my_args):
    """文章分类的详情页"""
    cate = get_object_or_404(Category, id=my_args)
    post_list = Post.objects.filter(category=cate)
    return render(request, 'blog_main_part/index.html', {'post_list': post_list})

comments/views.py
import markdown
from blog_main_part.models import Post
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentsForms


def post_comment(request, post_args):

    # 获取与评论相关联的那篇文章
    post = get_object_or_404(Post, id=post_args)

    # 当用户提交表单（POST）时，才处理表单数据
    if request.method != 'POST':
        # 不是POST请求，说明用户没提交数据，重新定向到详情页
        return redirect(post)

    else:
        # 把数据传入表单模型，并实例化
        form = CommentsForms(data=request.POST)

        # 检查表单是否符合格式要求
        if form.is_valid():
            # 合法，调用save方法保存，
            # commit=False作用是升舱恒实例，但还不保存到数据库
            comment = form.save(commit=False)
            # 将评论和被评论的文章关联起来
            comment.post = post
            # 最后将评论数据保存近数据库，调用模型实例的save方法
            comment.save()

            # 重定向到post的详情页
            return redirect(post)

        else:
            # 数据不合法，重新渲染详情页，再渲染表单的错误
            # 因为是关联的，post.comment_set.all()获取post下全部评论
            comment_list = post.comments.all()
            post.body = markdown.markdown(post.body,
                                          extensions=[
                                              'markdown.extensions.extra',
                                              'markdown.extensions.codehilite',
                                              'markdown.extensions.toc',
                                          ])
            return render(request, 'blog_main_part/detail.html', {'post': post,
                                                                  'form': form,
                                                                  'comment_list': comment_list})

blog_main_part/templates/blog_main_part/base.html
{% load blog_main_part_tags %}
<!DOCTYPE html>
<html>

    <head>
        <title>北极森林的小站</title>

        <!-- meta -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% load staticfiles %}
        <!-- css -->
        <link rel="stylesheet" href="{% static 'blog_main_part/css/reset_firstly.css' %}">
        <link rel="stylesheet" href="{% static 'blog_main_part/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="{% static 'blog_main_part/css/pace.css' %}">
        <link rel="stylesheet" href="{% static 'blog_main_part/css/custom.css' %}">

        <!-- js -->
        <script src="{% static 'blog_main_part/js/jquery-2.1.3.min.js' %}"></script>
        <script src="{% static 'blog_main_part/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog_main_part/js/pace.min.js' %}"></script>
        <script src="{% static 'blog_main_part/js/modernizr.custom.js' %}"></script>
    </head>

    <body>
        <div class="container">
            <header id="site-header">
                <div class="row">
                    <div class="col-md-4 col-sm-5 col-xs-8">
                        <div class="logo">
                            <h1>
                                <a href="{% url 'blog_main_part:index' %}">
                                    <b>北极森林的博客小站</b>
                                </a>
                            </h1>
                        </div>
                    </div>
                    <!-- col-md-4 -->
                    <div class="col-md-8 col-sm-7 col-xs-4">
                        <nav class="main-nav" role="navigation">
                            <div class="navbar-header">
                                <button type="button" id="trigger-overlay" class="navbar-toggle">
                                    <span class="ion-navicon"></span>
                                </button>
                            </div>

                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="cl-effect-11">
                                        <a href="{% url 'blog_main_part:index' %}" data-hover="Home">Home</a>
                                    </li>
                                </ul>
                            </div>
                            <!-- /.navbar-collapse -->
                        </nav>
                        <div id="header-search-box">
                            <a id="search-menu" href="#">
                                <span id="search-icon" class="ion-ios-search-strong"></span>
                            </a>
                            <div id="search-form" class="search-form">
                                <form role="search" method="get" id="searchform" action="#">
                                    <input type="search" placeholder="Search" required>
                                    <button type="submit">
                                        <span class="ion-ios-search-strong"></span>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!-- col-md-8 -->
                </div>
            </header>
        </div>
        <div class="copyrights">Collect from
            <a href="http://www.cssmoban.com/">网页模板</a>
        </div>

        <div class="content-body">
            <div class="container">
                <div class="row">
                    <main class="col-md-8">
                        {% block main %}{% endblock main %}
                    </main>
                    <aside class="col-md-4">
                        <div class="widget widget-recent-posts">
                            <h3 class="widget-title">最新文章</h3>
                            {% get_recent_posts as recent_post_list %}
                            <ul>
                                {% for post in recent_post_list %}
                                    <li>
                                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="widget widget-archives">
                            <h3 class="widget-title">归档时间</h3>
                            {% archives as date_list %}
                            <ul>
                                {% for date in date_list %}
                                    <li>
                                        <a href="{% url 'blog_main_part:archives' date.year date.month %}">{{ date.year }}
                                            年
                                            {{ date.month }}
                                            月</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>

                        <div class="widget widget-category">
                            <h3 class="widget-title">文章分类</h3>
                            {% get_categories as category_list %}
                            <ul>
                                {% for category in category_list %}
                                    <li>
                                        <a href="{% url 'blog_main_part:category' category.id %}">{{ category.name }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </aside>
                </div>
            </div>
        </div>
        <footer id="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <p class="copyright">&copy; 2017 北极森林的博客</p>
                    </div>
                </div>
            </div>
        </footer>

        <!-- Mobile Menu -->
        <div class="overlay overlay-hugeinc">
            <button type="button" class="overlay-close">
                <span class="ion-ios-close-empty"></span>
            </button>
            <nav>
                <ul>
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>
                        <a href="full-width.html">Blog</a>
                    </li>
                    <li>
                        <a href="about.html">About</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                </ul>
            </nav>
        </div>

        <script src="{% static 'blog_main_part/js/script.js' %}"></script>

    </body>

</html>

blog_main_part/templates/blog_main_part/detail.html
{% extends 'blog_main_part/base.html' %}

{% block main %}
	<article class="post post-1">
		<header class="entry-header">
			<h1 class="entry-title">{{ post.title }}</h1>
			<div class="entry-meta">

				<span class="post-views">
					<a href="#">阅读量：{{ post.views }}</a>
				</span>

				<span class="post-category">
					<a href="#">分类：{{ post.category.name }}</a>
				</span>

				<span class="post-date">
					<a href="#">
						<time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time>
					</a>
				</span>

				<span class="post-author">
					<a href="#">{{ post.author }}</a>
				</span>

				<span class="comments-link">
					<a href="{% url 'blog_main_part:detail' post.id %}">comment</a>
				</span>
			</div>
		</header>
		<div class="entry-content clearfix">
			{{ post.body|safe }}
		</div>
	</article>

	<section class="comment-area">
		<h2>留下你的想法</h2>
		<form action="{% url 'comments:post_comment' post.id %}" method="post" class="comment-form">
			{% csrf_token %}
			<div class="row">
				<div class="col-md-4">
					<label for="{{ form.name.id_for_label }}">Name:</label>
					{{ form.name }}
					{{ form.name.errors }}
				</div>
				<div class="col-md-4">
					<label for="{{ form.email.id_for_label }}">Email:</label>
					{{ form.email }}
					{{ form.email.errors }}
				</div>
				<div class="col-md-4">
					<label for="{{ form.url.id_for_label }}">Url:</label>
					{{ form.url }}
					{{ form.url.errors }}
				</div>
				<div class="col-md-12">
					<label for="{{ form.text.id_for_label }}">Comment:</label>
					{{ form.text }}
					{{ form.text.errors }}
					<button type="submit">
						<span>发表</span>
					</button>
				</div>
			</div>
		</form>
	</section>

	<section class="comment-list">
		<div class="comment_list" id="comments">
			<h2>评论列表</h2>
			<ul class="list-unstyled">
				{% for comment in comment_list %}
					<li class="comment-item">
						<span class="name">{{ comment.name }}</span>
					</li>
					<li class="comment-item">
						<time class="date">{{ comment.created_time }}</time>
					</li>
					<li class="comment-item">
						<div class="text">
							{{ comment.text }}
						</div>
					</li>

					{% empty %}
					暂无评论
				{% endfor %}
			</ul>
		</div>
	</section>

	<aside class="col-md-4">
		<div class="widget widget-recent-posts">
			<h3 class="widget-title">文章目录</h3>
			{{ toc|safe }}
		</div>
	</aside>

{% endblock main %}

blog_main_part/templates/blog_main_part/index.html
{% extends 'blog_main_part/base.html' %}

{% block main %}

    {% for post in post_list %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">

                    <span class="post-views">
                        <a href="#">阅读量：{{ post.views }}</a>
                    </span>

                    <span class="post-category">
                        <a href="#">分类：{{ post.category.name }}</a>
                    </span>

                    <span class="post-date">
                        <a href="#">
                            <time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time>
                        </a>
                    </span>

                    <span class="post-author">
                        <a href="#">{{ post.author }}</a>
                    </span>

                    <span class="comments-link">
                        <a href="#">4 Comments</a>
                    </span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读
                        <span class="meta-nav">→</span>
                    </a>
                </div>
            </div>
        </article>
        {% empty %}
        <div class="no-post">暂时还没发布文章！如人生一样空空如也呐……</div>
    {% endfor %}

{% endblock main %}